# Generated by Django 4.2.2 on 2023-06-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_eggs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eggs',
            new_name='Egg',
        ),
    ]
